version: "3"
services:
  bot:
    container_name: mk-rss
    build: .
    env_file: .env
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "3"
    restart: always
